### ISSUE TITLE
Clone , delete ans Mass Delete not Working

### ISSUE THREAD

**Issue by BenWallmeyer** [MonstreX/voyager-extension#74]
Hey can you help with this error?

voyager-extension-assets?path=js%2Fapp.js:2 Uncaught TypeError: Cannot read properties of null (reading 'dialog_remove_title')
    at voyager-extension-assets?path=js%2Fapp.js:2:51103
    at Array.reduce (<anonymous>)
    at t.trans (voyager-extension-assets?path=js%2Fapp.js:2:51073)
    at t.dialogActionRequest (voyager-extension-assets?path=js%2Fapp.js:2:53649)
    at HTMLAnchorElement.<anonymous> (todos:1457:18)
    at HTMLTableElement.dispatch (voyager-assets?path=js%2Fapp.js:2:1186056)
    at g.handle (voyager-assets?path=js%2Fapp.js:2:1184051)

**Comment by BenWallmeyer** [comment]
OK it works. You must create a new config file.
